5/14のまとめ
y15-glitch/skill-UP pull request #2
Opened 2023-05-14 10:58 UTC by y15-glitch

2023-05-16 14:28 UTC, cateiru requested changes
- PRがDraftになっていてレビュアーアサインされても通知来ないのでReady for Reaviewしてもらえるとありがたい。
- コンフリクトが起きていそうです。mainブランチに何故かpushされていそう

### Markdownについて

とりあえず、[基本的な書き方とフォーマットの構文 - GitHub Docs](https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 全部読んでまとめてもらうと良さそう。

### Git

追加で以下のことも書いてみてください。

- コミットログを1行づつ表示する
- `git cherry-pick`について
- マージとは？
- pushしていない状態で間違えてコミットしてしまったときの戻し方
- 特定のコミットを元に戻す（なかったこと）にする方法
- なぜ`git push -f`はいけないのか
- ステージングのファイル差分の表示と未ステージングの差分表示
- `git add`の取り消し
- サブモジュールについて

2023-05-16 14:28 UTC, cateiru commented on consolidate/README.md
> +###### **青字**保存完了
もし、書くとしたら普通に文字で書くか`>`つかって引用にしたり脚注を使う方法などがあります。

また、Markdownはサービスごとに独自の実装があり、[zennではメッセージ記法というものがあります](https://zenn.dev/zenn/articles/markdown-guide#%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)

2023-05-16 14:28 UTC, cateiru commented on consolidate/README.md
> +git switch -c "ファイル名"
[should]

ファイル名じゃなくてブランチ名っぽそう

2023-05-21 00:46 UTC, y15-glitch commented
#

2023-05-21 00:46 UTC, closed without merging